name: Maven Deploy to GitHub Packages

on:
  release:
    types: [ created ]

permissions:
  contents: read
  packages: write

jobs:
  github-deploy:
    runs-on: ubuntu-latest

    env:
      artifact_name: spring-app

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set project version from tag
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          mvn versions:set -DnewVersion=$VERSION

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}